[project]
name = "data-raw"
version = "0.1.0"
description = "Generate metadata for use in clim2parquet"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pathlib>=1.0.1",
    "ruff>=0.11.4",
]
